2018-06-17 18:49:30,339 ERROR: Exception on /index/ [GET] [in E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Users\Bouny\PycharmProjects\untitled\app\routes.py", line 32, in index
    return render_template("index.html", title='Home Page', form=form, posts=posts.order_by(Post.timestamp.desc()))
AttributeError: 'list' object has no attribute 'order_by'
2018-06-17 18:49:58,826 INFO: Microblog startup [in E:\Users\Bouny\PycharmProjects\untitled\app\__init__.py:30]
2018-06-17 18:50:43,915 INFO: Microblog startup [in E:\Users\Bouny\PycharmProjects\untitled\app\__init__.py:30]
2018-06-17 18:53:56,462 INFO: Microblog startup [in E:\Users\Bouny\PycharmProjects\untitled\app\__init__.py:30]
2018-06-17 18:55:21,891 INFO: Microblog startup [in E:\Users\Bouny\PycharmProjects\untitled\app\__init__.py:30]
2018-06-17 18:56:53,317 INFO: Microblog startup [in E:\Users\Bouny\PycharmProjects\untitled\app\__init__.py:30]
2018-06-17 19:01:21,999 INFO: Microblog startup [in E:\Users\Bouny\PycharmProjects\untitled\app\__init__.py:30]
2018-06-17 19:01:27,386 ERROR: Exception on /index/ [GET] [in E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Users\Bouny\PycharmProjects\untitled\app\routes.py", line 31, in index
    posts = Post.query.order_by(Post.timestamp.desc()).all().paginate(
AttributeError: 'list' object has no attribute 'paginate'
2018-06-17 19:01:50,273 INFO: Microblog startup [in E:\Users\Bouny\PycharmProjects\untitled\app\__init__.py:30]
2018-06-17 19:02:45,725 INFO: Microblog startup [in E:\Users\Bouny\PycharmProjects\untitled\app\__init__.py:30]
2018-06-17 19:03:20,779 INFO: Microblog startup [in E:\Users\Bouny\PycharmProjects\untitled\app\__init__.py:30]
2018-06-17 19:12:04,511 INFO: Microblog startup [in E:\Users\Bouny\PycharmProjects\untitled\app\__init__.py:30]
2018-06-17 19:12:05,889 ERROR: Exception on /user/Bouny [GET] [in E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "E:\Users\Bouny\PycharmProjects\untitled\app\routes.py", line 97, in user
    if posts.has_next else None
AttributeError: 'function' object has no attribute 'username'
2018-06-17 19:13:31,984 INFO: Microblog startup [in E:\Users\Bouny\PycharmProjects\untitled\app\__init__.py:30]
2018-06-17 19:13:35,187 ERROR: Exception on /user/Bouny [GET] [in E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "E:\Users\Bouny\PycharmProjects\untitled\app\routes.py", line 101, in user
    next_url=next_url, prev_url=prev_url)
  File "E:\Projects\Pycharm\envs\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "E:\Users\Bouny\PycharmProjects\untitled\app\templates\user.html", line 34, in template
    {% endblock %}
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\parser.py", line 213, in parse_if
    'name:endif'))
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "E:\Projects\Pycharm\envs\lib\site-packages\jinja2\parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2018-06-17 19:14:00,389 INFO: Microblog startup [in E:\Users\Bouny\PycharmProjects\untitled\app\__init__.py:30]
